@baseUrl = http://localhost:3000/api

### getPasiensBySearch
GET {{baseUrl}}/pasien/getPasiensBySearch?search=q222
Content-Type: application/json

### getNoRm
GET {{baseUrl}}/pasien/getNoRm
Content-Type: application/json

### getKodeReg
GET {{baseUrl}}/pasien/getKodeReg
Content-Type: application/json

### addTransPemeriksaanHeader
POST {{baseUrl}}/transperiksa/addTransPemeriksaanHeader
Content-Type: application/json

{
    "kode_reg":"P1",
    "id_pasien":1,
    "tanggal_periksa":"2026-03-14",
    "is_active":1,
    "id_analis_pemeriksa":1
}