@baseUrl = http://localhost:3000/api

### getPasiensBySearch
GET {{baseUrl}}/pasien/getPasiensBySearch?search=
Content-Type: application/json

### getNoRm
GET {{baseUrl}}/pasien/getNoRm
Content-Type: application/json

### getKodeReg
GET {{baseUrl}}/pasien/getKodeReg
Content-Type: application/json

### addTransPemeriksaanHeader
POST {{baseUrl}}/transperiksa/addTransPemeriksaanHeader
Content-Type: application/json

{
    "kode_reg":"P1",
    "id_pasien":1,
    "tanggal_periksa":"2026-03-14",
    "is_active":1,
    "id_analis_pemeriksa":1
}

### addTransPemeriksaanDetail
POST {{baseUrl}}/transperiksa/addTransPemeriksaanDetail
Content-Type: application/json

[
    {
        "id_tx_pemeriksaan":1,
        "id_sub_periksa":1,
        "hasil":"Non Reaktif",
        "nilai_normal":"Non Reaktif",
        "harga":70000,
        "is_active":1
    },
    {
        "id_tx_pemeriksaan":1,
        "id_sub_periksa":2,
        "hasil":"13,0",
        "nilai_normal":"P: 12,0 - 14,0 g/dl L 13,0 - 16,0 g/dl",
        "harga":100000,
        "is_active":1
    }
]

### hapusHasilPemeriksaanDetail
POST {{baseUrl}}/transperiksa/hapusHasilPemeriksaanDetail
Content-Type: application/json

{
    "id_tx_detail_pemeriksaan":9
}

### getPrintPdfPermintaanPemeriksaanLab
POST {{baseUrl}}/printpdf/getPrintPdfPermintaanPemeriksaanLab
Content-Type: application/json

{
    "kode_reg":"P1"
}

### getPrintPdfHasilPemeriksaanLab
POST {{baseUrl}}/printpdf/getPrintPdfHasilPemeriksaanLab
Content-Type: application/json

{
    "kode_reg":"P1"
}

### getPrintPdfBayarLab
POST {{baseUrl}}/printpdf/getPrintPdfBayarLab
Content-Type: application/json

{
    "kode_reg":"P1"
}

### getUserLogin
POST {{baseUrl}}/login/getUserLogin
Content-Type: application/json

{
    "username":"sindhu",
    "password":"paulus"
}

### REFRESH TOKEN
POST {{baseUrl}}/login/refreshToken
Content-Type: application/json
Cookie: refreshToken=ISI_REFRESH_TOKEN

### PROFILE
GET {{baseUrl}}/login/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VycyI6MSwicm9sZV91c2VyIjoic3VwZXJ1c2VyIiwiaWF0IjoxNzczNjQzMzYzLCJleHAiOjE3NzM2NDQyNjN9.7GWzqTmwmFUBTwc9fYPzyOzgPKm7Onl5pAgXZsaUlq0

### LOGOUT
POST {{baseUrl}}/login/logout
Cookie: refreshToken=ISI_TOKEN